# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build and Deploy to Container App Test

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build and Push Image
      run: |
        az acr login --name microhackcontainerregistryrajat --username ${{ secrets.ACR_USERNAME }} --password ${{ secrets.ACR_PASSWORD }} &&
        docker build -t microhackcontainerregistryrajat.azurecr.io/microhackapp:1 -f Dockerfile . &&
        docker push microhackcontainerregistryrajat.azurecr.io/microhackapp:1
